default: &default
  dispatchers:
    - polling_interval: <%= ENV.fetch("SOLID_QUEUE_DISPATCHER_POLLING_INTERVAL", 1) %>
      batch_size: <%= ENV.fetch("SOLID_QUEUE_DISPATCHER_BATCH_SIZE", 500) %>
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("SOLID_QUEUE_THREADS", 3) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: <%= ENV.fetch("SOLID_QUEUE_WORKER_POLLING_INTERVAL", 1) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
